### ISSUE TITLE
Beetl plugin breaks app hotreload process with NPE

### ISSUE THREAD

**Issue by greenlaw110** [actframework/act-beetl#3]
Beetl plugin breaks application hot reload with the following error:

```
java.lang.RuntimeException: 初始化失败
	at org.beetl.core.GroupTemplate.<init>(GroupTemplate.java:146)
	at act.view.beetl.BeetlView.init(BeetlView.java:56)
	at act.view.View.reload(View.java:60)
	at act.view.ViewManager.reload(ViewManager.java:64)
	at act.app.App.refresh(App.java:453)
	at act.app.App.refresh(App.java:417)
	at act.app.App.checkUpdates(App.java:328)
	at act.xio.NetworkHandler.handle(NetworkHandler.java:64)
	at act.xio.undertow.ActHttpHandler.handleRequest(ActHttpHandler.java:29)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:211)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:243)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:134)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:58)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:559)
Caused by: java.lang.NullPointerException: null
	at org.beetl.core.resource.ClasspathResourceLoader.init(ClasspathResourceLoader.java:221)
	at org.beetl.core.GroupTemplate.initResourceLoader(GroupTemplate.java:158)
	at org.beetl.core.GroupTemplate.<init>(GroupTemplate.java:142)
	... 16 common frames omitted
```

**Note**, this happens even I did nothing about beetl template and any method impact beetl template

**Comment by greenlaw110** [comment]
This is not a `act-beetl` issue. Should be fixed in ACT framework core
