### ISSUE TITLE
Server Error on invoking demo.view.ViewDemo.beetlInline  - org.beetl.core.exception.BeetlException: 

### ISSUE THREAD

**Issue by ghost** [actframework/act-beetl#8]
Error screenshot:
![image](https://user-images.githubusercontent.com/216930/56780965-b10c5e80-6824-11e9-961f-d5cdffbd7b06.png)

https://github.com/actframework/act-beetl/blob/4947ab1ce2d936574d6119044e69d2c33d326c60/src/main/java/act/view/beetl/BeetlView.java#L85

@Override
protected Template loadInlineTemplate(String content) {
    return new BeetlTemplate(content, this, true); //must be like this
}

Console log:

```
>>01:10:07:错找不到指定模板或者加载错(TEMPLATE_LOAD_ERROR): 位于0行 资源:Hello ${who} by ${templateId}
ClassLoader:act.app.DevModeClassLoader@5f67ea7b Path:beetl
2019-04-26 13:10:07,144 ERROR a.h.b.c.RequestHandlerProxy@[XNIO-1 task-1] - Server error encountered on handling request: [GET]/beetl/inline
org.beetl.core.exception.BeetlException: null
	at org.beetl.core.resource.ClasspathResource.openReader(ClasspathResource.java:74)
	at act.view.beetl.BeetlTemplateException$BeetlSourceInfo.<init>(BeetlTemplateException.java:109)
	at act.view.beetl.BeetlTemplateException.populateSourceInfo(BeetlTemplateException.java:50)
	at act.view.ActErrorResult.<init>(ActErrorResult.java:79)
	at act.view.TemplateException.<init>(TemplateException.java:37)
	at act.view.beetl.BeetlTemplateException.<init>(BeetlTemplateException.java:42)
	at act.view.beetl.BeetlTemplate.render(BeetlTemplate.java:91)
	at act.view.TemplateBase.merge(TemplateBase.java:90)
	at act.view.beetl.BeetlTemplate.merge(BeetlTemplate.java:57)
	at act.view.TemplateBase.merge(TemplateBase.java:48)
	at act.view.RenderTemplate.apply(RenderTemplate.java:80)
	at act.view.RenderAny.apply(RenderAny.java:66)
	at act.handler.builtin.controller.RequestHandlerProxy.onResult(RequestHandlerProxy.java:322)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:229)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1358)
	at act.route.Router$ContextualHandler.handle(Router.java:1748)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by greenlaw110** [comment]
Fixed in 1.5.0
